version: '3.8'

services:
  # 1. AWS Fake (LocalStack) - Simula S3, SQS, SNS, Lambda
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"            # Gateway único do LocalStack
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh" # Script para criar bucket/fila ao iniciar

  # 2. Banco de Dados
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: nexus_dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalog_db
    ports:
      - "5434:5432"

  # 3. Cache Distribuído
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 4. Observabilidade (Distributed Tracing)
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"